repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: https://github.com/myint/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake
        name: autoflake (python)
        args: [--in-place, --remove-all-unused-imports, --expand-star-imports , --remove-unused-variables, --recursive]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black, --line-length, "88"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black (python)
        exclude: _dag_template.py
        args: [--line-length, "88"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.950
  #   hooks:
  #    -  id: mypy
  #       name: mypy (python)
  #       files: torchrecsys/
  #       additional_dependencies: [pytest==6.2.4]
