repos:
  - repo: https://github.com/myint/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake
        name: autoflake (python)
        args: [--in-place, --remove-all-unused-imports, --expand-star-imports , --remove-unused-variables, --recursive]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black, --line-length, "88"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black (python)
        exclude: _dag_template.py
        args: [--line-length, "88"]
