name: Pylint autoflake, isort, black 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Python Linter
         uses: jiwidi/python-lint-action@main
