name: Pylint black, autoflake, isort

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Python Linter
         uses: jiwidi/python-lint-action@release
         with:
           source: "."
           isort-options: "-w 100"
